# Generated by Django 4.2.13 on 2024-07-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popplace', '0008_remove_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Stamp',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
