# Generated by Django 4.2.13 on 2024-07-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_member_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
