# Generated by Django 4.2.13 on 2024-07-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0009_alter_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='이름'),
        ),
    ]
