# Generated by Django 4.2.13 on 2024-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0010_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성')], max_length=6, null=True, verbose_name='성별'),
        ),
    ]
