# Generated by Django 4.2.13 on 2024-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0011_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.AddField(
            model_name='member',
            name='is_female',
            field=models.BooleanField(default=False, verbose_name='여성'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='남성'),
        ),
    ]
