# Generated by Django 4.2.13 on 2024-07-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0012_remove_member_gender_member_is_female_member_is_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Stamp',
        ),
    ]
