# Generated by Django 4.2.13 on 2024-07-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountapp', '0012_remove_member_gender_member_is_female_member_is_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stamp',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='stamp_code',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='stamp',
            name='user',
        ),
        migrations.AddField(
            model_name='stamp',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stamp',
            name='users',
            field=models.ManyToManyField(related_name='stamps', to=settings.AUTH_USER_MODEL),
        ),
    ]
