# Generated by Django 4.2.13 on 2024-07-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_female',
            field=models.BooleanField(default=False, verbose_name='여성'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='남성'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=64, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=40, verbose_name='비밀번호'),
        ),
    ]
