# Generated by Django 4.2.13 on 2024-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_female',
            field=models.BooleanField(default=False, verbose_name='여성'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_male',
            field=models.BooleanField(default=False, verbose_name='남성'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
